import { CommonModule } from '@angular/common';
import { Component, inject, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { EncuentroCiclo, EncuentroDashboard, EncuentroParticipante } from '../../../core/models/encuentro-poder.model';
import { EncuentroPoderService } from '../../../core/services/encuentro-poder.service';

@Component({
  selector: 'app-encuentro-dashboard', standalone: true, imports: [CommonModule, FormsModule, RouterLink],
  template: `<div class="page"><header class="heading"><div><span class="eyebrow">Módulo operativo</span><h1>Encuentro de Poder</h1></div><a routerLink="/encuentro-poder/ciclos/nuevo" class="button secondary">Nuevo ciclo</a></header>
    <section class="toolbar"><label>Ciclo<select [(ngModel)]="cicloSeleccionado" (ngModelChange)="cargar()"><option [ngValue]="null">Selecciona un ciclo</option>@for (c of ciclos; track c.id) {<option [ngValue]="c.id">{{ c.nombre }} · {{ c.estado }}</option>}</select></label>@if (dashboard) {<button class="button" (click)="exportar()">Exportar Excel</button><button class="button secondary" (click)="copiarEnlace()">Copiar enlace de inscripción</button>}</section>
    @if (enlaceCopiado) {<p class="notice">Enlace copiado al portapapeles.</p>}
    @if (dashboard; as data) {<section class="stats"><article><b>{{ data.inscritos }}</b><span>Inscritos</span></article><article><b>{{ data.conAsistencia }}</b><span>Con asistencia</span></article><article><b>{{ data.completos }}</b><span>Completos</span></article><article><b>{{ data.pendientes }}</b><span>Pendientes</span></article></section>
      <section class="grid"><article class="panel"><h2>Asistencia por clase</h2>@for (clase of data.clases; track clase.claseId) {<div class="class-row"><span>{{ clase.nombre }}</span><strong>{{ clase.presentes }} / {{ clase.inscritos }}</strong><div class="bar"><i [style.width.%]="porcentaje(clase.presentes, clase.inscritos)"></i></div></div>}</article><article class="panel"><h2>Tomar asistencia</h2><label>Clase<select [(ngModel)]="claseSeleccionada"><option [ngValue]="null">Selecciona una clase</option>@for (c of data.ciclo.clases; track c.id) { @if (c.obligatoria) {<option [ngValue]="c.id">{{ c.nombre }}</option>} }</select></label><input class="search" [(ngModel)]="busqueda" placeholder="Buscar por nombre o teléfono"><div class="attendees">@for (p of filtrados(data.participantes); track p.persona.id) {<div class="attendee"><div><strong>{{ p.persona.nombreCompleto }}</strong><small>{{ p.persona.telefono }}</small></div>@if (tieneClase(p, claseSeleccionada)) {<span class="present">Presente</span>} @else {<button class="mark" [disabled]="!claseSeleccionada || marcando === p.persona.id" (click)="marcar(p)">{{ marcando === p.persona.id ? '...' : 'Marcar' }}</button>}</div>}</div></article></section>
      <section class="panel"><h2>Estado de graduación</h2><div class="table-wrap"><table><thead><tr><th>Persona</th><th>Teléfono</th><th>Clases completadas</th><th>Faltantes</th><th>Estado</th><th></th></tr></thead><tbody>@for (p of data.participantes; track p.persona.id) {<tr><td>{{ p.persona.nombreCompleto }}</td><td>{{ p.persona.telefono }}</td><td>{{ p.clasesCompletadas }} / 3</td><td>{{ p.clasesFaltantes.join(', ') || '—' }}</td><td><span [class.complete]="p.estado === 'COMPLETO'" class="status">{{ p.estado }}</span></td><td><button class="link" (click)="verHistorial(p)">Historial</button></td></tr>}</tbody></table></div></section>
      @if (historial; as h) {<div class="modal-backdrop" (click)="historial = undefined"><article class="modal" (click)="$event.stopPropagation()"><button class="close" (click)="historial = undefined">×</button><h2>{{ h.persona.nombreCompleto }}</h2><p>{{ h.persona.telefono }} · {{ h.persona.comuna || 'Sin comuna' }}</p><h3>{{ h.estado }}</h3>@for (a of h.asistencias; track a.id) {<div class="history-row"><span>{{ a.clase }}</span><span>{{ a.fechaHora | date:'dd/MM/yyyy HH:mm' }}</span></div>} @if (!h.asistencias.length) {<p>No registra asistencias.</p>}</article></div>}
    } @else if (cargando) {<p class="muted">Cargando dashboard...</p>} @else {<div class="empty">Crea un ciclo para comenzar.</div>}
  </div>`,
  styles: [`:host{display:block;color:var(--text-primary)}.page{max-width:1280px;margin:0 auto;padding:28px 22px}.heading,.toolbar,.stats,.grid{display:flex;gap:16px}.heading{justify-content:space-between;align-items:center;margin-bottom:22px}.eyebrow{color:#7da9ff;font-weight:700}h1{font-size:34px;margin:6px 0 0}h2{margin-top:0;font-size:18px}.toolbar{align-items:end;flex-wrap:wrap;padding:16px;background:var(--bg-card);border:1px solid var(--border-color);border-radius:12px}.toolbar label,.panel label{display:grid;gap:6px;font-size:13px;font-weight:600}select,.search{min-width:240px;padding:10px;border:1px solid var(--border-color);border-radius:8px;background:var(--bg-secondary);color:var(--text-primary)}.button,.mark{border:0;border-radius:8px;background:#3978ee;color:white;padding:10px 14px;font-weight:700;text-decoration:none;cursor:pointer}.secondary{background:transparent;border:1px solid var(--border-color);color:var(--text-primary)}.notice,.empty{padding:14px;background:rgba(59,130,246,.12);border-radius:10px;margin:16px 0}.stats{margin:20px 0}.stats article{flex:1;padding:18px;background:var(--bg-card);border:1px solid var(--border-color);border-radius:12px}.stats b{display:block;font-size:28px}.stats span{color:var(--text-secondary);font-size:13px}.grid{align-items:start}.panel{flex:1;background:var(--bg-card);border:1px solid var(--border-color);border-radius:12px;padding:20px;margin-bottom:18px}.class-row{display:grid;grid-template-columns:1fr auto;gap:8px;margin:16px 0}.bar{grid-column:1/-1;height:7px;background:var(--bg-secondary);border-radius:9px;overflow:hidden}.bar i{display:block;height:100%;background:#4f8cff}.search{width:100%;box-sizing:border-box;margin:14px 0}.attendees{max-height:420px;overflow:auto}.attendee{display:flex;justify-content:space-between;align-items:center;padding:11px 0;border-bottom:1px solid var(--border-color)}small{display:block;color:var(--text-secondary);margin-top:3px}.present{color:#4ade80;font-weight:700}.mark{padding:7px 10px}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;padding:12px;border-bottom:1px solid var(--border-color);white-space:nowrap}.status{color:#fbbf24}.status.complete{color:#4ade80}.link{border:0;background:none;color:#75a6ff;cursor:pointer}.modal-backdrop{position:fixed;inset:0;background:#0008;display:grid;place-items:center;padding:20px}.modal{position:relative;background:var(--bg-card);border:1px solid var(--border-color);border-radius:14px;padding:26px;min-width:min(500px,100%)}.close{position:absolute;right:12px;top:8px;background:none;border:0;color:var(--text-primary);font-size:26px}.history-row{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--border-color)}.muted{color:var(--text-secondary)}@media(max-width:800px){.grid,.stats{display:grid;grid-template-columns:1fr}.heading{align-items:start}.stats article{display:flex;justify-content:space-between;align-items:center}}`],
})
export class EncuentroDashboardComponent implements OnInit {
  private service = inject(EncuentroPoderService);
  ciclos: EncuentroCiclo[] = []; cicloSeleccionado: number | null = null; claseSeleccionada: number | null = null; dashboard?: EncuentroDashboard; historial?: EncuentroParticipante; busqueda = ''; cargando = false; marcando: number | null = null; enlaceCopiado = false;
  ngOnInit(): void { this.service.ciclos().subscribe(c => { this.ciclos = c; if (c.length) { this.cicloSeleccionado = c[0].id; this.cargar(); } }); }
  cargar(): void { if (!this.cicloSeleccionado) return; this.cargando = true; this.service.dashboard(this.cicloSeleccionado).subscribe({ next: d => { this.dashboard = d; this.cargando = false; this.claseSeleccionada = d.ciclo.clases.find(c => c.obligatoria)?.id ?? null; }, error: () => this.cargando = false }); }
  porcentaje(a: number, b: number): number { return b ? Math.round(a / b * 100) : 0; }
  filtrados(data: EncuentroParticipante[]): EncuentroParticipante[] { const q = this.busqueda.toLowerCase().trim(); return q ? data.filter(p => `${p.persona.nombreCompleto} ${p.persona.telefono}`.toLowerCase().includes(q)) : data; }
  tieneClase(p: EncuentroParticipante, claseId: number | null): boolean { return !!claseId && p.asistencias.some(a => a.claseId === claseId); }
  marcar(p: EncuentroParticipante): void { if (!this.claseSeleccionada) return; this.marcando = p.persona.id; this.service.registrarAsistencia(p.persona.id, this.claseSeleccionada).subscribe({ next: () => { this.marcando = null; this.cargar(); }, error: () => this.marcando = null }); }
  verHistorial(p: EncuentroParticipante): void { this.service.historial(p.persona.id).subscribe(h => this.historial = h); }
  exportar(): void { if (!this.cicloSeleccionado) return; this.service.exportar(this.cicloSeleccionado).subscribe(blob => { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `encuentro_poder_${this.cicloSeleccionado}.xlsx`; anchor.click(); URL.revokeObjectURL(url); }); }
  copiarEnlace(): void { const ciclo = this.ciclos.find(c => c.id === this.cicloSeleccionado); if (!ciclo) return; navigator.clipboard?.writeText(`${window.location.origin}/inscripcion-encuentro/${ciclo.publicToken}`); this.enlaceCopiado = true; setTimeout(() => this.enlaceCopiado = false, 2200); }
}
